package kernel

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
)

// Variables declared with := at the top level of a cell are "hoisted": the
// kernel type-checks the cell, declares them as package-level variables in
// gopyter_vars.go and turns the := into an assignment. Each program then
// restores their values when it starts and saves them (with encoding/gob)
// when main returns, so later cells, which are new processes, see them.

// VarInfo describes a variable hoisted from a top-level := statement.
type VarInfo struct {
	// Type is the variable type, qualified by package path. It keys the
	// saved value, so a variable redefined with another type starts over.
	Type string
	// Imports are those of its declaration (alias -> path).
	Imports map[string]string
}

const varsFile = "gopyter_vars.go"

// VarsDir is where the values of hoisted variables are saved.
func (k *Kernel) VarsDir() string { return filepath.Join(k.Dir, "gopyter_vars") }

func (k *Kernel) varsStatusPath() string { return filepath.Join(k.VarsDir(), "status.json") }

func (k *Kernel) removeVarFile(name string) error {
	err := os.Remove(filepath.Join(k.VarsDir(), varFileName(name)))
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	return err
}

// varFileName must match gopyterVarPath in helpersSrc. Hex keeps names
// distinct on case-insensitive file systems.
func varFileName(name string) string { return hex.EncodeToString([]byte(name)) + ".gob" }

// writeVars generates gopyter_vars.go for the hoisted variables in decls.
func (k *Kernel) writeVars(decls []*Decl) error {
	var vars []*Decl
	imps := map[string]string{}
	for _, d := range decls {
		if d.Var != nil {
			vars = append(vars, d)
			maps.Copy(imps, d.Var.Imports)
		}
	}
	var b strings.Builder
	b.WriteString("// Code generated by gopyter. DO NOT EDIT.\npackage main\n\n")
	if len(imps) > 0 {
		b.WriteString("import (\n")
		for _, alias := range slices.Sorted(maps.Keys(imps)) {
			b.WriteString("\t")
			b.WriteString(alias)
			b.WriteString(" ")
			b.WriteString(strconv.Quote(imps[alias]))
			b.WriteString("\n")
		}
		b.WriteString(")\n\n")
	}
	// Called by a deferred call in main().
	b.WriteString("func gopyterSaveVars() {\n")
	for _, d := range vars {
		b.WriteString("\tgopyterSaveVar(")
		b.WriteString(strconv.Quote(d.Names[0]))
		b.WriteString(", ")
		b.WriteString(strconv.Quote(d.Var.Type))
		b.WriteString(", ")
		b.WriteString(d.Names[0])
		b.WriteString(")\n")
	}
	b.WriteString("\tgopyterVarsDone()\n}\n\n")
	for _, d := range vars {
		b.WriteString(d.Src)
		b.WriteString("\n\n")
	}
	return os.WriteFile(filepath.Join(k.Dir, varsFile), []byte(b.String()), 0o644)
}

// hoist type-checks the cell with its variables kept local and decides
// how each define is emitted. It returns the declarations for the hoisted
// variables and functions. decls are the declarations of the other cells.
// On any problem nothing is hoisted, and the build reports the errors.
func (k *Kernel) hoist(ctx context.Context, cellID string, pc *parsedCell, decls []*Decl, imps []*Import) (map[*define]hoist, []*Decl) {
	// Keep the variables this cell hoisted when it last ran, like the
	// program will: "a := a + 1" re-run reads the saved a.
	have := map[string]bool{}
	for _, d := range decls {
		for _, n := range d.Names {
			have[n] = true
		}
	}
	k.mu.Lock()
	for _, d := range k.decls {
		if d.CellID == cellID && d.Var != nil && !have[d.Names[0]] {
			decls = append(slices.Clip(decls), d)
		}
	}
	k.mu.Unlock()

	local := *pc
	local.render(nil)
	local.body = local.plain // a void trailing call is not a type error
	src, _ := k.generate(decls, imps, &local)
	if err := os.WriteFile(filepath.Join(k.Dir, "main.go"), []byte(src), 0o644); err != nil {
		return nil, nil
	}
	if err := k.writeVars(decls); err != nil {
		return nil, nil
	}
	cfg := &packages.Config{
		Context: ctx,
		Mode:    packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedSyntax | packages.NeedImports,
		Dir:     k.Dir,
		Env:     k.goCmd(ctx).Env,
	}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil || len(pkgs) != 1 || pkgs[0].Types == nil || pkgs[0].TypesInfo == nil {
		return nil, nil
	}
	pkg := pkgs[0]
	for _, e := range pkg.Errors {
		// Hoisting fixes unused variables, and the plain body has the
		// trailing expression unwrapped. Other errors (like a variable used
		// before its :=, which hoisting would hide) stop hoisting.
		if !strings.Contains(e.Msg, "declared and not used") && !strings.Contains(e.Msg, "is not used") {
			return nil, nil
		}
	}
	return hoistDecisions(cellID, pc, pkg.Fset, pkg.Types, pkg.TypesInfo, pkg.Syntax)
}

type cellPosKey struct {
	name      string
	line, col int
}

func hoistDecisions(cellID string, pc *parsedCell, fset *token.FileSet, main *types.Package, info *types.Info, files []*ast.File) (map[*define]hoist, []*Decl) {
	inCell := func(p token.Pos) (token.Position, bool) {
		pos := fset.Position(p)
		f := pos.Filename
		return pos, f == pc.name || strings.HasSuffix(f, string(filepath.Separator)+pc.name)
	}
	// Variables defined by the cell, by position.
	defs := map[cellPosKey]*types.Var{}
	for id, obj := range info.Defs {
		v, ok := obj.(*types.Var)
		if !ok || v.IsField() {
			continue
		}
		if pos, ok := inCell(id.Pos()); ok {
			defs[cellPosKey{id.Name, pos.Line, pos.Column}] = v
		}
	}
	// Function literals of the cell, by position.
	lits := map[[2]int]*ast.FuncLit{}
	for _, f := range files {
		ast.Inspect(f, func(n ast.Node) bool {
			if lit, ok := n.(*ast.FuncLit); ok {
				if pos, ok := inCell(lit.Pos()); ok {
					lits[[2]int{pos.Line, pos.Column}] = lit
				}
			}
			return true
		})
	}

	how := map[*define]hoist{}
	hoisted := map[*types.Var]bool{}
	vars := map[*define][]*types.Var{}
	for _, d := range pc.defines {
		var vs []*types.Var
		for _, id := range d.idents {
			v := defs[cellPosKey(id)]
			if v == nil {
				// Reused (or unknown) on the left of :=: leave it alone.
				vs = nil
				break
			}
			vs = append(vs, v)
		}
		if len(vs) == 0 {
			continue
		}
		vars[d] = vs
		if d.fn != nil {
			how[d] = hoistFunc // tentatively, checked below
		} else if !slices.ContainsFunc(vs, func(v *types.Var) bool { return !nameable(v.Type(), main) }) {
			how[d] = hoistVar
		} else {
			continue
		}
		for _, v := range vs {
			hoisted[v] = true
		}
	}

	// A function literal moves to package level, so it may only capture
	// variables that are hoisted too. Dropping one can invalidate another.
	for changed := true; changed; {
		changed = false
		for _, d := range pc.defines {
			if how[d] != hoistFunc {
				continue
			}
			lit := lits[[2]int{d.fn.line, d.fn.col}]
			if lit == nil || !capturesOnly(lit, main, info, hoisted) {
				delete(how, d)
				hoisted[vars[d][0]] = false
				changed = true
			}
		}
	}

	var out []*Decl
	for _, d := range pc.defines {
		switch how[d] {
		case hoistVar:
			for i, v := range vars[d] {
				out = append(out, varDecl(cellID, pc.name, d.idents[i], v, main))
			}
		case hoistFunc:
			id := d.idents[0]
			fn := pc.src[d.fn.start:d.fn.end]
			var src strings.Builder
			src.WriteString(lineDirective(pc.name, id.line, id.col))
			src.WriteString("var ")
			src.WriteString(id.name)
			src.WriteString(" = ")
			// Keep the literal's own position for error messages.
			fmt.Fprintf(&src, "/*line %s:%d:%d*/", pc.name, d.fn.line, d.fn.col)
			src.WriteString(fn)
			out = append(out, &Decl{
				Names:  []string{id.name},
				Src:    src.String(),
				Raw:    "var " + id.name + " = " + fn,
				CellID: cellID,
			})
		}
	}
	return how, out
}

// capturesOnly reports whether lit only refers to variables of main() that
// are hoisted.
func capturesOnly(lit *ast.FuncLit, main *types.Package, info *types.Info, hoisted map[*types.Var]bool) bool {
	ok := true
	ast.Inspect(lit, func(n ast.Node) bool {
		id, isID := n.(*ast.Ident)
		if !isID || !ok {
			return ok
		}
		v, isVar := info.Uses[id].(*types.Var)
		if !isVar || v.IsField() || v.Pkg() != main || v.Parent() == main.Scope() || v.Parent() == nil {
			return true
		}
		if v.Pos() >= lit.Pos() && v.Pos() < lit.End() {
			return true // declared inside the literal
		}
		ok = hoisted[v]
		return ok
	})
	return ok
}

func varDecl(cellID, cellName string, id defIdent, v *types.Var, main *types.Package) *Decl {
	imps := map[string]string{}
	typ := types.TypeString(v.Type(), func(p *types.Package) string {
		if p == main {
			return ""
		}
		alias := pkgAlias(p.Path())
		imps[alias] = p.Path()
		return alias
	})
	key := types.TypeString(v.Type(), func(p *types.Package) string {
		if p == main {
			return ""
		}
		return p.Path()
	})
	raw := "var " + id.name + " " + types.TypeString(v.Type(), func(p *types.Package) string {
		if p == main {
			return ""
		}
		return p.Name()
	})
	var src strings.Builder
	src.WriteString(lineDirective(cellName, id.line, id.col))
	// Initialized by loading, so package-level vars using it come after.
	fmt.Fprintf(&src, "var %s %s = gopyterLoadVar[%s](%s, %s)", id.name, typ, typ, strconv.Quote(id.name), strconv.Quote(key))
	return &Decl{
		Names:  []string{id.name},
		Src:    src.String(),
		Raw:    raw,
		CellID: cellID,
		Var:    &VarInfo{Type: key, Imports: imps},
	}
}

// pkgAlias is the import name of path in gopyter_vars.go, chosen so it
// can't clash with the user's identifiers.
func pkgAlias(path string) string {
	var b strings.Builder
	b.WriteString("gopyterpkg_")
	for _, r := range path {
		if r < 128 && (r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')) {
			b.WriteRune(r)
		} else {
			fmt.Fprintf(&b, "_%x_", r)
		}
	}
	return b.String()
}

// nameable reports whether t can be written at package level of main.
func nameable(t types.Type, main *types.Package) bool {
	seen := map[types.Type]bool{}
	var ok func(types.Type) bool
	obj := func(o *types.TypeName, args *types.TypeList) bool {
		if p := o.Pkg(); p != nil {
			if p == main {
				if o.Parent() != main.Scope() {
					return false // declared inside a function
				}
			} else if !o.Exported() || !importable(p.Path()) {
				return false
			}
		}
		for t := range args.Types() {
			if !ok(t) {
				return false
			}
		}
		return true
	}
	ok = func(t types.Type) bool {
		if seen[t] {
			return true
		}
		seen[t] = true
		switch t := t.(type) {
		case *types.Basic:
			return t.Kind() != types.UnsafePointer && t.Info()&types.IsUntyped == 0 && t.Kind() != types.Invalid
		case *types.Named:
			return obj(t.Obj(), t.TypeArgs())
		case *types.Alias:
			return obj(t.Obj(), t.TypeArgs())
		case *types.Pointer:
			return ok(t.Elem())
		case *types.Slice:
			return ok(t.Elem())
		case *types.Array:
			return ok(t.Elem())
		case *types.Chan:
			return ok(t.Elem())
		case *types.Map:
			return ok(t.Key()) && ok(t.Elem())
		case *types.Signature:
			return t.TypeParams() == nil && ok(t.Params()) && ok(t.Results())
		case *types.Tuple:
			for v := range t.Variables() {
				if !ok(v.Type()) {
					return false
				}
			}
			return true
		case *types.Struct:
			for f := range t.Fields() {
				if (!f.Exported() && f.Pkg() != main) || !ok(f.Type()) {
					return false
				}
			}
			return true
		case *types.Interface:
			for m := range t.ExplicitMethods() {
				if (!m.Exported() && m.Pkg() != main) || !ok(m.Type()) {
					return false
				}
			}
			for e := range t.EmbeddedTypes() {
				if !ok(e) {
					return false
				}
			}
			return true
		}
		return false // type parameters, unions
	}
	return ok(t)
}

func importable(path string) bool {
	if path == "main" {
		return false
	}
	return !slices.Contains(strings.Split(path, "/"), "internal")
}

// varsStatus is written by gopyterVarsDone when a program saved the
// hoisted variables.
type varsStatus struct {
	Errors map[string]string `json:"errors"`
}

// afterRun reconciles the hoisted variables with what the program saved.
// A variable defined by this cell that could not be saved is forgotten,
// so later cells fail to compile instead of seeing a zero value.
func (k *Kernel) afterRun(cellID string, emit func(Event)) {
	var st varsStatus
	b, err := os.ReadFile(k.varsStatusPath())
	saved := err == nil && json.Unmarshal(b, &st) == nil

	k.mu.Lock()
	var lost, reset, notes []string
	decls := k.decls[:0:0]
	for _, d := range k.decls {
		if d.Var == nil {
			decls = append(decls, d)
			continue
		}
		name := d.Names[0]
		reason, failed := st.Errors[name]
		switch {
		case !saved && d.CellID == cellID:
			lost = append(lost, name)
		case failed && d.CellID == cellID:
			notes = append(notes, fmt.Sprintf("%s is not kept for later cells: %s", name, reason))
		case failed:
			reset = append(reset, name)
			notes = append(notes, fmt.Sprintf("%s could not be saved, later cells see its zero value: %s", name, reason))
		default:
			decls = append(decls, d)
			continue
		}
		if d.CellID == cellID {
			// Forget the variable.
			if err := k.removeVarFile(name); err != nil {
				notes = append(notes, err.Error())
			}
			continue
		}
		decls = append(decls, d)
	}
	for _, name := range reset {
		if err := k.removeVarFile(name); err != nil {
			notes = append(notes, err.Error())
		}
	}
	k.decls = decls
	k.mu.Unlock()

	if len(lost) > 0 {
		notes = append(notes, fmt.Sprintf("not kept for later cells (the program stopped before saving them): %s", strings.Join(lost, ", ")))
	}
	for _, n := range notes {
		emit(Event{Kind: Info, Text: n})
	}
}
