// Package kernel implements a Go "kernel": it accumulates declarations across
// notebook cells, generates a Go program for each execution, compiles it and
// streams its output back. The approach is inspired by GoNB
// (https://github.com/janpfeifer/gonb).
package kernel

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"io"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"slices"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"golang.org/x/tools/imports"
)

// EventKind identifies the type of output produced by an execution.
type EventKind int

const (
	Stdout EventKind = iota
	Stderr
	Result   // text/plain value produced by Display or a trailing expression
	Markdown // text/markdown produced by DisplayMarkdown
	Error    // compile or kernel error
	Info     // kernel informational message
	Image    // base64 image/png produced by Display (of an image.Image) or DisplayPNG
)

// Event is a piece of output streamed from an execution.
type Event struct {
	Kind EventKind
	Text string
	// ID is set for output shown with DisplayID or DisplayMarkdownID:
	// a later event with the same ID replaces the earlier output.
	ID string
}

// Version is the gopyter version reported by %version.
var Version = "dev"

// ErrCompile is returned when the cell fails to compile.
var ErrCompile = errors.New("compilation failed")

// ErrInterrupted is returned when an execution is cancelled.
var ErrInterrupted = errors.New("interrupted")

// Kernel holds the state of a Go session.
type Kernel struct {
	// Dir is the workspace (Go module) where programs are built.
	Dir string
	// RunDir is the working directory of executed programs.
	RunDir string

	mu      sync.Mutex
	checkMu sync.Mutex // serializes Check, which reuses one directory
	ownsDir bool
	decls   []*Decl
	imports []*Import
	// resolved is the full import list of the last successful build,
	// including imports added by goimports (used for completion).
	resolved  []*Import
	env       map[string]string
	args      []string
	goflags   []string // extra go build flags (%goflags)
	noAutoGet bool     // %noautoget: don't fetch missing modules
	goVersion string
}

const helpersSrc = `// Code generated by gopyter. DO NOT EDIT.
package main

// Imports are aliased so they can't clash with package-level names of the
// notebook (e.g. a variable called url or bytes).
import (
	gopyter_bytes "bytes"
	gopyter_base64 "encoding/base64"
	gopyter_gob "encoding/gob"
	gopyter_hex "encoding/hex"
	gopyter_json "encoding/json"
	gopyter_flag "flag"
	gopyter_fmt "fmt"
	gopyter_image "image"
	gopyter_png "image/png"
	gopyter_url "net/url"
	gopyter_os "os"
	gopyter_filepath "path/filepath"
	gopyter_reflect "reflect"
	gopyter_strings "strings"
	gopyter_sync "sync"
)

var (
	gopyterOut = gopyter_os.NewFile(3, "gopyter")
	gopyterMu  gopyter_sync.Mutex
)

// Cache returns the value stored under key, calling fn and storing its
// result (gob-encoded, in the kernel workspace) only the first time. Every
// cell is a fresh process, so this is how an expensive global is computed
// once: var resp = Cache("resp", func() T { ... }).
// Unexported struct fields are not saved. Use %cache clear to recompute.
func Cache[T any](key string, fn func() T) T {
	var v T
	if gopyterCacheLoad(key, &v) {
		return v
	}
	v = fn()
	gopyterCacheStore(key, v)
	return v
}

// CacheErr is like Cache for functions that can fail: a result is stored
// only when fn returns a nil error, so failures are retried next time.
func CacheErr[T any](key string, fn func() (T, error)) (T, error) {
	var v T
	if gopyterCacheLoad(key, &v) {
		return v, nil
	}
	v, err := fn()
	if err == nil {
		gopyterCacheStore(key, v)
	}
	return v, err
}

func gopyterCachePath(key string) string {
	dir := gopyter_os.Getenv("GOPYTER_CACHE_DIR")
	if dir == "" {
		return ""
	}
	return gopyter_filepath.Join(dir, gopyter_url.PathEscape(key)+".gob")
}

func gopyterCacheLoad(key string, v any) bool {
	path := gopyterCachePath(key)
	if path == "" {
		return false
	}
	f, err := gopyter_os.Open(path)
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()
	if err := gopyter_gob.NewDecoder(f).Decode(v); err != nil {
		gopyter_fmt.Fprintf(gopyter_os.Stderr, "gopyter: cache %q unreadable, recomputing: %v\n", key, err)
		return false
	}
	return true
}

func gopyterCacheStore(key string, v any) {
	path := gopyterCachePath(key)
	if path == "" {
		return
	}
	var buf gopyter_bytes.Buffer
	err := gopyter_gob.NewEncoder(&buf).Encode(v)
	if err == nil {
		err = gopyterWriteFile(path, buf.Bytes())
	}
	if err != nil {
		gopyter_fmt.Fprintf(gopyter_os.Stderr, "gopyter: cache %q not saved: %v\n", key, err)
	}
}

// gopyterWriteFile writes then renames, so an interrupted run never leaves
// a torn file.
func gopyterWriteFile(path string, data []byte) error {
	if err := gopyter_os.MkdirAll(gopyter_filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := gopyter_os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return gopyter_os.Rename(tmp, path)
}

// Variables declared with := at the top level of a cell are declared at
// package level (in gopyter_vars.go), loaded when the program starts and
// saved when main returns.

var gopyterVarErrs = map[string]string{}

// gopyterError stands in for error values that gob can't encode.
type gopyterError struct{ Msg string }

func (e gopyterError) Error() string { return e.Msg }

// gopyterGobReady is referenced by gopyterLoadVar: variables are loaded
// while initializing package-level variables, before init functions run,
// and Go initializes dependencies first.
var gopyterGobReady = func() bool {
	gopyter_gob.Register(gopyterError{})
	return true
}()

func gopyterVarPath(name string) string {
	dir := gopyter_os.Getenv("GOPYTER_VARS_DIR")
	if dir == "" {
		return ""
	}
	return gopyter_filepath.Join(dir, gopyter_hex.EncodeToString([]byte(name))+".gob")
}

// gopyterLoadVar returns the saved value of a variable, or its zero value
// when none was saved with this type.
func gopyterLoadVar[T any](name, typ string) (v T) {
	path := gopyterVarPath(name)
	if path == "" || !gopyterGobReady {
		return v
	}
	f, err := gopyter_os.Open(path)
	if err != nil {
		return v
	}
	defer func() { _ = f.Close() }()
	dec := gopyter_gob.NewDecoder(f)
	var saved string
	if err := dec.Decode(&saved); err != nil || saved != typ {
		return v // redefined with another type
	}
	// Boxed, so nil pointers and interfaces are fine.
	var box struct{ V T }
	if err := dec.Decode(&box); err != nil {
		gopyter_fmt.Fprintf(gopyter_os.Stderr, "gopyter: %s not restored: %v\n", name, err)
		return v
	}
	return box.V
}

func gopyterEncodeVar[T any](typ string, v T) ([]byte, error) {
	var buf gopyter_bytes.Buffer
	enc := gopyter_gob.NewEncoder(&buf)
	err := enc.Encode(typ)
	if err == nil {
		err = enc.Encode(struct{ V T }{v})
	}
	return buf.Bytes(), err
}

func gopyterSaveVar[T any](name, typ string, v T) {
	path := gopyterVarPath(name)
	if path == "" {
		return
	}
	switch k := gopyter_reflect.TypeFor[T]().Kind(); k {
	case gopyter_reflect.Func, gopyter_reflect.Chan, gopyter_reflect.UnsafePointer:
		gopyterVarErrs[name] = gopyter_fmt.Sprintf("%s values can't be saved", k)
		return
	}
	data, err := gopyterEncodeVar(typ, v)
	if e, ok := any(&v).(*error); ok && err != nil && *e != nil {
		// Most error types can't be encoded: keep the message.
		*e = gopyterError{(*e).Error()}
		data, err = gopyterEncodeVar(typ, v)
	}
	if err == nil {
		err = gopyterWriteFile(path, data)
	}
	if err != nil {
		gopyterVarErrs[name] = err.Error()
	}
}

// gopyterVarsDone tells the kernel that the variables were saved.
func gopyterVarsDone() {
	dir := gopyter_os.Getenv("GOPYTER_VARS_DIR")
	if dir == "" {
		return
	}
	b, _ := gopyter_json.Marshal(map[string]any{"errors": gopyterVarErrs})
	if err := gopyterWriteFile(gopyter_filepath.Join(dir, "status.json"), b); err != nil {
		gopyter_fmt.Fprintf(gopyter_os.Stderr, "gopyter: variables not saved: %v\n", err)
	}
}

// gopyterEmit sends a rich result to the kernel; plain is printed instead
// when there's no kernel to receive it (e.g. on Windows). Outputs with an
// id replace the previous output with that id.
func gopyterEmit(mime, data, plain, id string) {
	gopyterMu.Lock()
	defer gopyterMu.Unlock()
	m := map[string]string{"mime": mime, "data": data}
	if id != "" {
		m["id"] = id
	}
	b, _ := gopyter_json.Marshal(m)
	if _, err := gopyterOut.Write(append(b, '\n')); err != nil {
		gopyter_fmt.Println(plain)
	}
}

// gopyterParseFlags parses the command line, for cells using %% or %exec.
func gopyterParseFlags() {
	if !gopyter_flag.Parsed() {
		gopyter_flag.Parse()
	}
}

// Display shows the given values as the cell's result. Images
// (image.Image) are drawn in the output.
func Display(vs ...any) {
	var parts []string
	emitted := false
	flush := func() {
		if len(parts) > 0 {
			s := gopyter_strings.Join(parts, ", ")
			gopyterEmit("text/plain", s, s, "")
			parts, emitted = nil, true
		}
	}
	for _, v := range vs {
		if img, ok := v.(gopyter_image.Image); ok && !gopyterIsNil(v) {
			flush()
			gopyterDisplayImage(img, "")
			emitted = true
			continue
		}
		parts = append(parts, gopyter_fmt.Sprintf("%+v", v))
	}
	flush()
	if !emitted {
		gopyterEmit("text/plain", "", "", "")
	}
}

// DisplayID is like Display, but the output can be updated: calling it
// again with the same id replaces what the earlier call showed, e.g. to
// animate an image or show progress. A single image is drawn; other values
// are shown as text.
func DisplayID(id string, vs ...any) {
	if len(vs) == 1 {
		if img, ok := vs[0].(gopyter_image.Image); ok && !gopyterIsNil(vs[0]) {
			gopyterDisplayImage(img, id)
			return
		}
	}
	parts := make([]string, len(vs))
	for i, v := range vs {
		parts[i] = gopyter_fmt.Sprintf("%+v", v)
	}
	s := gopyter_strings.Join(parts, ", ")
	gopyterEmit("text/plain", s, s, id)
}

// DisplayMarkdownID is like DisplayMarkdown, but calling it again with
// the same id replaces the earlier output (see DisplayID).
func DisplayMarkdownID(id, s string) { gopyterEmit("text/markdown", s, s, id) }

// gopyterIsNil reports a nil pointer stored in an interface, like a nil
// *image.RGBA, whose methods would panic.
func gopyterIsNil(v any) bool {
	rv := gopyter_reflect.ValueOf(v)
	return rv.Kind() == gopyter_reflect.Pointer && rv.IsNil()
}

func gopyterDisplayImage(img gopyter_image.Image, id string) {
	var buf gopyter_bytes.Buffer
	if err := gopyter_png.Encode(&buf, img); err != nil {
		gopyter_fmt.Fprintf(gopyter_os.Stderr, "gopyter: can't display image: %v\n", err)
		return
	}
	gopyterEmit("image/png", gopyter_base64.StdEncoding.EncodeToString(buf.Bytes()), "[image/png]", id)
}

// DisplayPNG shows PNG encoded image data in the cell's output.
func DisplayPNG(data []byte) {
	gopyterEmit("image/png", gopyter_base64.StdEncoding.EncodeToString(data), "[image/png]", "")
}

// DisplayMarkdown renders s as markdown in the cell's output.
func DisplayMarkdown(s string) { gopyterEmit("text/markdown", s, s, "") }
`

// New creates a kernel. If dir is empty a temporary workspace is created.
func New(dir string) (*Kernel, error) {
	k := &Kernel{Dir: dir, env: map[string]string{}}
	if dir == "" {
		d, err := os.MkdirTemp("", "gopyter-kernel-*")
		if err != nil {
			return nil, err
		}
		k.Dir, k.ownsDir = d, true
	} else if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	if _, err := exec.LookPath("go"); err != nil {
		return nil, fmt.Errorf("the go toolchain was not found in PATH: %w", err)
	}
	if _, err := os.Stat(filepath.Join(k.Dir, "go.mod")); err != nil {
		out, err := k.goCmd(context.Background(), "mod", "init", "gopyter.local/kernel").CombinedOutput()
		if err != nil {
			return nil, fmt.Errorf("go mod init: %v: %s", err, out)
		}
	}
	if err := os.WriteFile(filepath.Join(k.Dir, "gopyter_helpers.go"), []byte(helpersSrc), 0o644); err != nil {
		return nil, err
	}
	if out, err := k.goCmd(context.Background(), "env", "GOVERSION").Output(); err == nil {
		k.goVersion = strings.TrimSpace(string(out))
	} else {
		k.goVersion = runtime.Version()
	}
	return k, nil
}

// GoVersion reports the version of the Go toolchain in use.
func (k *Kernel) GoVersion() string { return k.goVersion }

// Close removes the temporary workspace, if owned.
func (k *Kernel) Close() error {
	if k.ownsDir {
		return os.RemoveAll(k.Dir)
	}
	return nil
}

// Reset clears all accumulated declarations and saved variables.
func (k *Kernel) Reset() error {
	k.mu.Lock()
	defer k.mu.Unlock()
	k.decls, k.imports = nil, nil
	return os.RemoveAll(k.VarsDir())
}

// Declarations returns a sorted list of declared identifiers.
func (k *Kernel) Declarations() []string {
	k.mu.Lock()
	defer k.mu.Unlock()
	var out []string
	for _, d := range k.decls {
		for _, n := range d.Names {
			if !strings.Contains(n, "#") {
				out = append(out, n)
			}
		}
	}
	sort.Strings(out)
	return out
}

func (k *Kernel) goCmd(ctx context.Context, args ...string) *exec.Cmd {
	cmd := exec.CommandContext(ctx, "go", args...)
	cmd.Dir = k.Dir
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	return cmd
}

// CacheDir is where Cache and CacheErr store values.
func (k *Kernel) CacheDir() string { return filepath.Join(k.Dir, "gopyter_cache") }

// CacheKeys lists the keys stored by Cache and CacheErr.
func (k *Kernel) CacheKeys() ([]string, error) {
	ents, err := os.ReadDir(k.CacheDir())
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var keys []string
	for _, e := range ents {
		name, ok := strings.CutSuffix(e.Name(), ".gob")
		if !ok || e.IsDir() {
			continue
		}
		if key, err := url.PathUnescape(name); err == nil {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	return keys, nil
}

// ClearCache deletes the given cache keys, or every key when none is given.
// It returns the keys that were removed.
func (k *Kernel) ClearCache(keys ...string) ([]string, error) {
	if len(keys) == 0 {
		all, err := k.CacheKeys()
		if err != nil {
			return nil, err
		}
		keys = all
	}
	var removed []string
	for _, key := range keys {
		err := os.Remove(filepath.Join(k.CacheDir(), url.PathEscape(key)+".gob"))
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return removed, err
		}
		removed = append(removed, key)
	}
	return removed, nil
}

// Remove forgets the declarations (and imports, by path or name) with the
// given names. Removing a type also removes its methods. A declaration that
// declares several names (var a, b = ...) is removed as a whole. It returns
// the names that were actually removed.
func (k *Kernel) Remove(names ...string) []string {
	k.mu.Lock()
	defer k.mu.Unlock()
	want := map[string]bool{}
	for _, n := range names {
		want[n] = true
	}
	matches := func(n string) bool {
		typ, _, isMethod := strings.Cut(n, ".")
		return want[n] || (isMethod && want[typ])
	}
	var removed []string
	decls := k.decls[:0:0]
	for _, d := range k.decls {
		if slices.ContainsFunc(d.Names, matches) {
			if d.Var != nil {
				// Forgotten, so a later variable of that name starts over.
				_ = k.removeVarFile(d.Names[0]) // best effort: it only goes stale
			}
			for _, n := range d.Names {
				if !strings.Contains(n, "#") {
					removed = append(removed, n)
				}
			}
			continue
		}
		decls = append(decls, d)
	}
	imps := k.imports[:0:0]
	for _, i := range k.imports {
		if want[i.Path] || (i.Name != "" && want[i.Name]) {
			removed = append(removed, strconv.Quote(i.Path))
			continue
		}
		imps = append(imps, i)
	}
	k.decls, k.imports = decls, imps
	return removed
}

func (k *Kernel) environ() []string {
	env := os.Environ()
	env = append(env, "GOPYTER_CACHE_DIR="+k.CacheDir(), "GOPYTER_VARS_DIR="+k.VarsDir())
	for key, v := range k.env {
		env = append(env, key+"="+v)
	}
	return env
}

// Execute runs a cell. cellID identifies the cell (re-executing a cell
// replaces its previous declarations), name is used in error positions.
// Output is streamed through emit; calls to emit are serialized. The
// cell's programs get no input; see ExecuteInput.
func (k *Kernel) Execute(ctx context.Context, cellID, name, src string, emit func(Event)) error {
	return k.ExecuteInput(ctx, cellID, name, src, nil, emit)
}

// ExecuteInput is Execute with stdin as the standard input of the cell's
// program and shell commands (nil for none).
func (k *Kernel) ExecuteInput(ctx context.Context, cellID, name, src string, stdin io.Reader, emit func(Event)) error {
	// Output arrives from several goroutines (stdout, stderr, display);
	// serialize it so emit never needs to be safe for concurrent use.
	// %capture copies it to a file, under the same lock.
	var emitMu sync.Mutex
	var capture *os.File
	unsafeEmit := emit
	emit = func(e Event) {
		emitMu.Lock()
		defer emitMu.Unlock()
		unsafeEmit(e)
		if capture != nil {
			writeCapture(capture, e)
		}
	}
	defer func() {
		emitMu.Lock()
		defer emitMu.Unlock()
		if capture != nil {
			_ = capture.Close() // best effort: the output was shown anyway
		}
	}()

	pc, err := parseCell(cellID, name, src)
	if err != nil {
		emit(Event{Kind: Error, Text: cleanErrors(err.Error(), k.Dir)})
		return ErrCompile
	}

	for _, c := range pc.commands {
		if f, ok, err := k.openCapture(c); ok {
			if err != nil {
				return err
			}
			emitMu.Lock()
			if capture != nil {
				_ = capture.Close() // a second %capture wins
			}
			capture = f
			emitMu.Unlock()
			continue
		}
		if err := k.runCommand(ctx, c, stdin, emit); err != nil {
			return err
		}
	}
	if !pc.hasCode {
		return nil
	}

	// A %test cell is built with go test, from a _test.go file. Only one
	// of the two files may exist, or the declarations would clash.
	mainPath, stale := filepath.Join(k.Dir, "main.go"), filepath.Join(k.Dir, "main_test.go")
	if pc.test {
		mainPath, stale = stale, mainPath
	}
	if err := os.Remove(stale); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}

	var decls []*Decl
	var imps, resolved []*Import
	write := func() error {
		var src string
		src, resolved = k.generate(decls, imps, pc)
		if err := os.WriteFile(mainPath, []byte(src), 0o644); err != nil {
			return err
		}
		return writeVars(k.Dir, decls)
	}
	// prepare decides which variables are hoisted, which needs the
	// dependencies (it is repeated after fetching modules).
	prepare := func() error {
		decls, imps = k.merge(cellID, pc.decls, pc.imports)
		if len(pc.defines) > 0 {
			how, extra := k.hoist(ctx, k.Dir, k.goCmd(ctx).Env, cellID, pc, decls, imps)
			pc.render(how)
			if len(extra) > 0 {
				decls, imps = k.merge(cellID, append(slices.Clip(pc.decls), extra...), pc.imports)
			}
		}
		return write()
	}
	if err := prepare(); err != nil {
		return err
	}

	bin := filepath.Join(k.Dir, "gopyter_exec")
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	k.mu.Lock()
	build := []string{"build"}
	if pc.test {
		build = []string{"test", "-c"}
	}
	build = append(append(build, k.goflags...), "-o", bin, ".")
	autoGet := !k.noAutoGet
	k.mu.Unlock()
	fetched := false
	for {
		out, err := k.goCmd(ctx, build...).CombinedOutput()
		if ctx.Err() != nil {
			return ErrInterrupted
		}
		if err == nil {
			break
		}
		if pc.body != pc.plain && strings.Contains(string(out), "used as value") {
			// The trailing call returns no value: don't display it.
			pc.body = pc.plain
			if err := write(); err != nil {
				return err
			}
			continue
		}
		if missing := missingModules(string(out)); autoGet && !fetched && len(missing) > 0 {
			fetched = true
			for _, p := range missing {
				emit(Event{Kind: Info, Text: "go get " + p})
				if gout, gerr := k.goCmd(ctx, "get", p).CombinedOutput(); gerr != nil {
					emit(Event{Kind: Error, Text: strings.TrimSpace(string(gout))})
					return ErrCompile
				}
			}
			if err := prepare(); err != nil {
				return err
			}
			continue
		}
		emit(Event{Kind: Error, Text: cleanErrors(string(out), k.Dir)})
		return ErrCompile
	}

	// Compilation succeeded: commit the declarations.
	k.mu.Lock()
	k.decls, k.imports, k.resolved = decls, imps, resolved
	args := append([]string(nil), k.args...)
	k.mu.Unlock()
	switch {
	case pc.test:
		args = pc.testArgs()
	case pc.hasArgs:
		args = pc.args
	}

	if err := os.Remove(k.varsStatusPath()); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	err = k.run(ctx, bin, args, stdin, emit)
	if pc.userMain == "" && !pc.test {
		// A cell's own func main doesn't save the variables, and
		// neither does a test binary, which never calls main.
		k.afterRun(cellID, emit)
	}
	return err
}

// merge returns the declarations and imports of the other cells, minus
// those replaced by newDecls and newImps, followed by the new ones.
func (k *Kernel) merge(cellID string, newDecls []*Decl, newImps []*Import) ([]*Decl, []*Import) {
	k.mu.Lock()
	defer k.mu.Unlock()
	newNames := map[string]bool{}
	for _, d := range newDecls {
		for _, n := range d.Names {
			newNames[n] = true
		}
	}
	var decls []*Decl
	for _, d := range k.decls {
		if d.CellID == cellID {
			continue
		}
		clash := false
		for _, n := range d.Names {
			if newNames[n] {
				clash = true
				break
			}
		}
		if !clash {
			decls = append(decls, d)
		}
	}
	decls = append(decls, newDecls...)

	newPaths := map[string]bool{}
	for _, i := range newImps {
		newPaths[i.Path] = true
	}
	var imps []*Import
	for _, i := range k.imports {
		if i.CellID != cellID && !newPaths[i.Path] {
			imps = append(imps, i)
		}
	}
	imps = append(imps, newImps...)
	return decls, imps
}

func writeImports(b *strings.Builder, imps []*Import) {
	if len(imps) == 0 {
		return
	}
	b.WriteString("import (\n")
	for _, i := range imps {
		b.WriteString("\t")
		if i.Name != "" {
			b.WriteString(i.Name)
			b.WriteString(" ")
		}
		b.WriteString(strconv.Quote(i.Path))
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

func (k *Kernel) generate(decls []*Decl, imps []*Import, pc *parsedCell) (string, []*Import) {
	var body strings.Builder
	for _, d := range decls {
		if d.Var != nil {
			continue // in gopyter_vars.go
		}
		body.WriteString(d.Src)
		body.WriteString("\n\n")
	}
	if pc.userMain != "" {
		body.WriteString(pc.userMain)
		body.WriteString("\n")
	} else {
		// Deferred so the variables are also saved when the cell panics.
		body.WriteString("func main() {\ndefer gopyterSaveVars()\n")
		if pc.parseFlags {
			body.WriteString("gopyterParseFlags()\n")
		}
		if pc.exec != "" {
			// Positioned at the %exec line, for errors like an unknown
			// function.
			body.WriteString(lineDirective(pc.name, pc.execLine, 1))
			body.WriteString(pc.exec)
			body.WriteString("()\n")
		}
		body.WriteString(pc.body)
		body.WriteString("\n}\n")
	}

	var draft strings.Builder
	draft.WriteString("package main\n\n")
	writeImports(&draft, imps)
	draft.WriteString(body.String())

	// Let goimports add missing and remove unused imports, then keep only
	// the resulting import list so our //line directives stay intact.
	finalImps := imps
	if fixed, err := imports.Process(filepath.Join(k.Dir, "main.go"), []byte(draft.String()), nil); err == nil {
		if f, err := parser.ParseFile(token.NewFileSet(), "", fixed, parser.ImportsOnly); err == nil {
			finalImps = nil
			for _, is := range f.Imports {
				imp := &Import{Path: strings.Trim(is.Path.Value, "\"`")}
				if is.Name != nil {
					imp.Name = is.Name.Name
				}
				finalImps = append(finalImps, imp)
			}
		}
	}

	var out strings.Builder
	out.WriteString("// Code generated by gopyter. DO NOT EDIT.\npackage main\n\n")
	writeImports(&out, finalImps)
	out.WriteString(body.String())
	return out.String(), finalImps
}

var missingRe = regexp.MustCompile(`no required module provides package ([^\s;:]+)`)

func missingModules(out string) []string {
	seen := map[string]bool{}
	var res []string
	for _, m := range missingRe.FindAllStringSubmatch(out, -1) {
		if !seen[m[1]] {
			seen[m[1]] = true
			res = append(res, m[1])
		}
	}
	return res
}

func cleanErrors(s, dir string) string {
	var out []string
	for l := range strings.SplitSeq(strings.TrimSpace(s), "\n") {
		if strings.HasPrefix(l, "# ") {
			continue
		}
		l = strings.ReplaceAll(l, dir+string(filepath.Separator), "")
		l = strings.TrimPrefix(l, "./")
		out = append(out, l)
	}
	return strings.Join(out, "\n")
}

func (k *Kernel) run(ctx context.Context, bin string, args []string, stdin io.Reader, emit func(Event)) error {
	cmd := exec.CommandContext(ctx, bin, args...)
	cmd.Dir = k.RunDir
	cmd.Env = k.environ()
	cmd.Stdin = stdin
	cmd.WaitDelay = 2 * time.Second
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return err
	}
	// Rich results (Display/DisplayMarkdown) are sent through file
	// descriptor 3; on Windows they fall back to stdout.
	dr, dw, err := os.Pipe()
	if err != nil {
		return err
	}
	if runtime.GOOS != "windows" {
		cmd.ExtraFiles = []*os.File{dw}
	}
	if err := cmd.Start(); err != nil {
		_ = dr.Close()
		_ = dw.Close()
		return err
	}
	// The child holds its own copy of the write end.
	_ = dw.Close()

	var wg sync.WaitGroup
	wg.Add(3)
	go func() { defer wg.Done(); pump(stdout, Stdout, emit) }()
	go func() { defer wg.Done(); pump(stderr, Stderr, emit) }()
	go func() {
		defer wg.Done()
		defer func() { _ = dr.Close() }()
		sc := bufio.NewScanner(dr)
		sc.Buffer(make([]byte, 64*1024), 64*1024*1024)
		for sc.Scan() {
			var m struct{ Mime, Data, ID string }
			if json.Unmarshal(sc.Bytes(), &m) != nil {
				continue
			}
			kind := Result
			switch m.Mime {
			case "text/markdown":
				kind = Markdown
			case "image/png":
				kind = Image
			}
			emit(Event{Kind: kind, Text: m.Data, ID: m.ID})
		}
		if err := sc.Err(); err != nil {
			emit(Event{Kind: Error, Text: "display output: " + err.Error()})
			// Keep draining so the program never blocks on a full pipe.
			_, _ = io.Copy(io.Discard, dr)
		}
	}()
	wg.Wait()
	err = cmd.Wait()
	if ctx.Err() != nil {
		return ErrInterrupted
	}
	if ee, ok := errors.AsType[*exec.ExitError](err); ok {
		return fmt.Errorf("exit status %d", ee.ExitCode())
	}
	return err
}

func pump(r io.Reader, kind EventKind, emit func(Event)) {
	buf := make([]byte, 32*1024)
	for {
		n, err := r.Read(buf)
		if n > 0 {
			emit(Event{Kind: kind, Text: string(bytes.Clone(buf[:n]))})
		}
		if err != nil {
			return
		}
	}
}

// runShell runs script with the system shell in dir.
func (k *Kernel) runShell(ctx context.Context, script, dir string, stdin io.Reader, emit func(Event)) error {
	cmd := exec.CommandContext(ctx, "sh", "-c", script)
	if runtime.GOOS == "windows" {
		cmd = exec.CommandContext(ctx, "cmd", "/C", script)
	}
	cmd.Dir = dir
	cmd.Env = append(k.environ(), "GOWORK=off")
	cmd.Stdin = stdin
	cmd.WaitDelay = 2 * time.Second
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return err
	}
	if err := cmd.Start(); err != nil {
		return err
	}
	var wg sync.WaitGroup
	wg.Add(2)
	go func() { defer wg.Done(); pump(stdout, Stdout, emit) }()
	go func() { defer wg.Done(); pump(stderr, Stderr, emit) }()
	wg.Wait()
	if err := cmd.Wait(); err != nil {
		if ctx.Err() != nil {
			return ErrInterrupted
		}
		return err
	}
	return nil
}

// runCommand executes a shell command, magic or cell magic.
func (k *Kernel) runCommand(ctx context.Context, c Command, stdin io.Reader, emit func(Event)) error {
	if !c.Magic {
		err := k.runShell(ctx, c.Text, k.Dir, stdin, emit)
		if err != nil && !errors.Is(err, ErrInterrupted) {
			return fmt.Errorf("!%s: %w", c.Text, err)
		}
		return err
	}
	if c.Cell {
		return k.cellMagic(ctx, c, emit)
	}

	fields, err := splitArgs(c.Text)
	if err != nil {
		return fmt.Errorf("%%%s: %w", c.Text, err)
	}
	if len(fields) == 0 {
		return nil
	}
	switch fields[0] {
	case "reset":
		if len(fields) > 1 && fields[1] == "go.mod" {
			return k.resetGoMod(ctx, emit)
		}
		if err := k.Reset(); err != nil {
			return err
		}
		emit(Event{Kind: Info, Text: "kernel state cleared"})
	case "goflags":
		k.mu.Lock()
		if len(fields) > 1 {
			// GoNB: %goflags "" clears them.
			k.goflags = slices.DeleteFunc(slices.Clone(fields[1:]), func(s string) bool { return s == "" })
		}
		flags := strings.Join(k.goflags, " ")
		k.mu.Unlock()
		if flags == "" {
			flags = "(none)"
		}
		emit(Event{Kind: Info, Text: "go build flags: " + flags})
	case "autoget", "noautoget":
		k.mu.Lock()
		k.noAutoGet = fields[0] == "noautoget"
		k.mu.Unlock()
		if fields[0] == "autoget" {
			emit(Event{Kind: Info, Text: "missing modules are fetched with go get"})
		} else {
			emit(Event{Kind: Info, Text: "missing modules are not fetched: use !go get"})
		}
	case "version":
		emit(Event{Kind: Stdout, Text: "gopyter " + Version + ", " + k.goVersion + "\n"})
	case "env":
		if len(fields) == 1 {
			k.mu.Lock()
			for key, v := range k.env {
				emit(Event{Kind: Stdout, Text: key + "=" + v + "\n"})
			}
			k.mu.Unlock()
			return nil
		}
		for _, kv := range fields[1:] {
			key, v, ok := strings.Cut(kv, "=")
			if !ok {
				return fmt.Errorf("%%env: expected KEY=VALUE, got %q", kv)
			}
			k.mu.Lock()
			k.env[key] = v
			k.mu.Unlock()
			emit(Event{Kind: Info, Text: "set " + key})
		}
	case "args":
		k.mu.Lock()
		k.args = fields[1:]
		k.mu.Unlock()
		emit(Event{Kind: Info, Text: "program args: " + strings.Join(fields[1:], " ")})
	case "rm":
		if len(fields) == 1 {
			return errors.New("%rm: expected names to remove (see %ls)")
		}
		if removed := k.Remove(fields[1:]...); len(removed) == 0 {
			emit(Event{Kind: Info, Text: "nothing to remove"})
		} else {
			emit(Event{Kind: Info, Text: "removed " + strings.Join(removed, ", ")})
		}
	case "cache":
		return k.cacheMagic(fields[1:], emit)
	case "ls", "who":
		names := k.Declarations()
		if len(names) == 0 {
			emit(Event{Kind: Info, Text: "no declarations"})
		} else {
			emit(Event{Kind: Stdout, Text: strings.Join(names, "\n") + "\n"})
		}
	case "workspace":
		emit(Event{Kind: Stdout, Text: k.Dir + "\n"})
	case "help":
		emit(Event{Kind: Markdown, Text: MagicHelp})
	default:
		return fmt.Errorf("unknown magic %%%s (try %%help)", fields[0])
	}
	return nil
}

func (k *Kernel) cacheMagic(args []string, emit func(Event)) error {
	if len(args) == 0 {
		keys, err := k.CacheKeys()
		if err != nil {
			return err
		}
		if len(keys) == 0 {
			emit(Event{Kind: Info, Text: "cache is empty"})
		} else {
			emit(Event{Kind: Stdout, Text: strings.Join(keys, "\n") + "\n"})
		}
		return nil
	}
	if args[0] != "clear" {
		return fmt.Errorf("%%cache: unknown subcommand %q (use %%cache or %%cache clear [keys])", args[0])
	}
	removed, err := k.ClearCache(args[1:]...)
	if err != nil {
		return err
	}
	if len(removed) == 0 {
		emit(Event{Kind: Info, Text: "nothing to clear"})
	} else {
		emit(Event{Kind: Info, Text: "cleared " + strings.Join(removed, ", ")})
	}
	return nil
}

// MagicHelp documents the special cell commands.
const MagicHelp = "## Cell commands\n\n" +
	"| Command | Description |\n|---|---|\n" +
	"| `!cmd` | run a shell command in the kernel workspace (e.g. `!go get github.com/foo/bar`); `!*cmd` is the same, and a trailing `\\` continues the command on the next line |\n" +
	"| `%reset` | forget all declarations and saved variables |\n" +
	"| `%reset go.mod` | start the workspace's `go.mod` over, dropping its modules |\n" +
	"| `%env KEY=VALUE` | set environment variables for executed programs |\n" +
	"| `%args a b c` | set command line arguments for executed programs |\n" +
	"| `%%` or `%main [args]` | parse flags (`flag.Parse()`) first, with these arguments for this cell only |\n" +
	"| `%exec fn [args]` | run `fn()` instead of statements, after parsing flags |\n" +
	"| `%test [flags]` | build with `go test` and run the cell's `Test`/`Benchmark` functions (or pass flags, e.g. `-test.run=.`) |\n" +
	"| `%goflags [flags]` | show or set extra `go build` flags, e.g. `-race` or `-tags=x`; `%goflags \"\"` clears them |\n" +
	"| `%autoget`, `%noautoget` | fetch missing modules automatically (the default), or not |\n" +
	"| `%capture [-a] file` | also write this cell's output to a file (`-a` appends) |\n" +
	"| `%ls` | list persisted declarations |\n" +
	"| `%rm name...` | forget declarations (a type's methods too) or imports |\n" +
	"| `%cache` | list values stored by `Cache`/`CacheErr` |\n" +
	"| `%cache clear [key...]` | delete cached values so they are recomputed |\n" +
	"| `%workspace` | print the kernel workspace directory |\n" +
	"| `%version` | print the gopyter and Go versions |\n\n" +
	"Cell magics take the rest of the cell, and must be its first line:\n\n" +
	"| Cell magic | Description |\n|---|---|\n" +
	"| `%%writefile [-a] file` | write the cell to a file (`-a` appends) |\n" +
	"| `%%bash`, `%%sh` | run the cell as a shell script |\n" +
	"| `%%script cmd` | run `cmd` with the cell as its input, e.g. `%%script python3` |\n\n" +
	"Magics can also be written as `//gonb:%...`, as in GoNB. " +
	"Files and scripts are relative to the directory programs run in.\n\n" +
	"Top level `func`, `type`, `var`, `const` and `import` declarations persist across cells. " +
	"Everything else runs inside `main()`. A trailing expression is displayed as the result. " +
	"Each cell can have its own `func init()` (or GoNB's `init_xxx()`). " +
	"Variables declared with `:=` at the top level of a cell are kept too: their values are saved " +
	"with `encoding/gob` when the cell ends and restored in later cells (exported fields only; " +
	"values that can't be saved, like channels or mutexes, are not kept). " +
	"Use `Display(v)` and `DisplayMarkdown(s)` for rich output; `Display` draws an `image.Image` " +
	"(so does a trailing image expression), and `DisplayPNG(data)` shows PNG bytes. " +
	"`DisplayID(id, v)` and `DisplayMarkdownID(id, s)` replace their earlier output with the same id, " +
	"for animations and progress. Programs can read their standard input: type it in the line " +
	"under the running cell.\n\n" +
	"Each cell runs in a fresh process, so a persisted `var` is re-initialized every time. " +
	"Wrap expensive initializers to compute them once: " +
	"`var resp, err = CacheErr(\"resp\", func() (*T, error) { ... })`."
