// Package kernel implements a Go "kernel": it accumulates declarations across
// notebook cells, generates a Go program for each execution, compiles it and
// streams its output back. The approach is inspired by GoNB
// (https://github.com/janpfeifer/gonb).
package kernel

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go/parser"
	"go/token"
	"io"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"slices"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"

	"golang.org/x/tools/imports"
)

// EventKind identifies the type of output produced by an execution.
type EventKind int

const (
	Stdout EventKind = iota
	Stderr
	Result   // text/plain value produced by Display or a trailing expression
	Markdown // text/markdown produced by DisplayMarkdown
	Error    // compile or kernel error
	Info     // kernel informational message
)

// Event is a piece of output streamed from an execution.
type Event struct {
	Kind EventKind
	Text string
}

// ErrCompile is returned when the cell fails to compile.
var ErrCompile = errors.New("compilation failed")

// ErrInterrupted is returned when an execution is cancelled.
var ErrInterrupted = errors.New("interrupted")

// Kernel holds the state of a Go session.
type Kernel struct {
	// Dir is the workspace (Go module) where programs are built.
	Dir string
	// RunDir is the working directory of executed programs.
	RunDir string

	mu      sync.Mutex
	ownsDir bool
	decls   []*Decl
	imports []*Import
	// resolved is the full import list of the last successful build,
	// including imports added by goimports (used for completion).
	resolved  []*Import
	env       map[string]string
	args      []string
	seq       int
	goVersion string
}

const helpersSrc = `// Code generated by gopyter. DO NOT EDIT.
package main

import (
	"bytes"
	"encoding/gob"
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

var (
	gopyterOut = os.NewFile(3, "gopyter")
	gopyterMu  sync.Mutex
)

// Cache returns the value stored under key, calling fn and storing its
// result (gob-encoded, in the kernel workspace) only the first time. Every
// cell is a fresh process, so this is how an expensive global is computed
// once: var resp = Cache("resp", func() T { ... }).
// Unexported struct fields are not saved. Use %cache clear to recompute.
func Cache[T any](key string, fn func() T) T {
	var v T
	if gopyterCacheLoad(key, &v) {
		return v
	}
	v = fn()
	gopyterCacheStore(key, v)
	return v
}

// CacheErr is like Cache for functions that can fail: a result is stored
// only when fn returns a nil error, so failures are retried next time.
func CacheErr[T any](key string, fn func() (T, error)) (T, error) {
	var v T
	if gopyterCacheLoad(key, &v) {
		return v, nil
	}
	v, err := fn()
	if err == nil {
		gopyterCacheStore(key, v)
	}
	return v, err
}

func gopyterCachePath(key string) string {
	dir := os.Getenv("GOPYTER_CACHE_DIR")
	if dir == "" {
		return ""
	}
	return filepath.Join(dir, url.PathEscape(key)+".gob")
}

func gopyterCacheLoad(key string, v any) bool {
	path := gopyterCachePath(key)
	if path == "" {
		return false
	}
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()
	if err := gob.NewDecoder(f).Decode(v); err != nil {
		fmt.Fprintf(os.Stderr, "gopyter: cache %q unreadable, recomputing: %v\n", key, err)
		return false
	}
	return true
}

func gopyterCacheStore(key string, v any) {
	path := gopyterCachePath(key)
	if path == "" {
		return
	}
	var buf bytes.Buffer
	err := gob.NewEncoder(&buf).Encode(v)
	if err == nil {
		err = os.MkdirAll(filepath.Dir(path), 0o755)
	}
	if err == nil {
		// Write then rename so an interrupted run never leaves a torn file.
		tmp := path + ".tmp"
		if err = os.WriteFile(tmp, buf.Bytes(), 0o644); err == nil {
			err = os.Rename(tmp, path)
		}
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "gopyter: cache %q not saved: %v\n", key, err)
	}
}

func gopyterEmit(mime, data string) {
	gopyterMu.Lock()
	defer gopyterMu.Unlock()
	b, _ := json.Marshal(map[string]string{"mime": mime, "data": data})
	if _, err := gopyterOut.Write(append(b, '\n')); err != nil {
		fmt.Println(data)
	}
}

// Display shows the given values as the cell's result.
func Display(vs ...any) {
	parts := make([]string, len(vs))
	for i, v := range vs {
		parts[i] = fmt.Sprintf("%+v", v)
	}
	gopyterEmit("text/plain", strings.Join(parts, ", "))
}

// DisplayMarkdown renders s as markdown in the cell's output.
func DisplayMarkdown(s string) { gopyterEmit("text/markdown", s) }
`

// New creates a kernel. If dir is empty a temporary workspace is created.
func New(dir string) (*Kernel, error) {
	k := &Kernel{Dir: dir, env: map[string]string{}}
	if dir == "" {
		d, err := os.MkdirTemp("", "gopyter-kernel-*")
		if err != nil {
			return nil, err
		}
		k.Dir, k.ownsDir = d, true
	} else if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	if _, err := exec.LookPath("go"); err != nil {
		return nil, fmt.Errorf("the go toolchain was not found in PATH: %w", err)
	}
	if _, err := os.Stat(filepath.Join(k.Dir, "go.mod")); err != nil {
		out, err := k.goCmd(context.Background(), "mod", "init", "gopyter.local/kernel").CombinedOutput()
		if err != nil {
			return nil, fmt.Errorf("go mod init: %v: %s", err, out)
		}
	}
	if err := os.WriteFile(filepath.Join(k.Dir, "gopyter_helpers.go"), []byte(helpersSrc), 0o644); err != nil {
		return nil, err
	}
	if out, err := k.goCmd(context.Background(), "env", "GOVERSION").Output(); err == nil {
		k.goVersion = strings.TrimSpace(string(out))
	} else {
		k.goVersion = runtime.Version()
	}
	return k, nil
}

// GoVersion reports the version of the Go toolchain in use.
func (k *Kernel) GoVersion() string { return k.goVersion }

// Close removes the temporary workspace, if owned.
func (k *Kernel) Close() error {
	if k.ownsDir {
		return os.RemoveAll(k.Dir)
	}
	return nil
}

// Reset clears all accumulated declarations.
func (k *Kernel) Reset() {
	k.mu.Lock()
	defer k.mu.Unlock()
	k.decls, k.imports = nil, nil
}

// Declarations returns a sorted list of declared identifiers.
func (k *Kernel) Declarations() []string {
	k.mu.Lock()
	defer k.mu.Unlock()
	var out []string
	for _, d := range k.decls {
		for _, n := range d.Names {
			if !strings.Contains(n, "#") {
				out = append(out, n)
			}
		}
	}
	sort.Strings(out)
	return out
}

func (k *Kernel) goCmd(ctx context.Context, args ...string) *exec.Cmd {
	cmd := exec.CommandContext(ctx, "go", args...)
	cmd.Dir = k.Dir
	cmd.Env = append(os.Environ(), "GOWORK=off", "GOFLAGS=-mod=mod")
	return cmd
}

// CacheDir is where Cache and CacheErr store values.
func (k *Kernel) CacheDir() string { return filepath.Join(k.Dir, "gopyter_cache") }

// CacheKeys lists the keys stored by Cache and CacheErr.
func (k *Kernel) CacheKeys() ([]string, error) {
	ents, err := os.ReadDir(k.CacheDir())
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var keys []string
	for _, e := range ents {
		name, ok := strings.CutSuffix(e.Name(), ".gob")
		if !ok || e.IsDir() {
			continue
		}
		if key, err := url.PathUnescape(name); err == nil {
			keys = append(keys, key)
		}
	}
	sort.Strings(keys)
	return keys, nil
}

// ClearCache deletes the given cache keys, or every key when none is given.
// It returns the keys that were removed.
func (k *Kernel) ClearCache(keys ...string) ([]string, error) {
	if len(keys) == 0 {
		all, err := k.CacheKeys()
		if err != nil {
			return nil, err
		}
		keys = all
	}
	var removed []string
	for _, key := range keys {
		err := os.Remove(filepath.Join(k.CacheDir(), url.PathEscape(key)+".gob"))
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return removed, err
		}
		removed = append(removed, key)
	}
	return removed, nil
}

// Remove forgets the declarations (and imports, by path or name) with the
// given names. Removing a type also removes its methods. A declaration that
// declares several names (var a, b = ...) is removed as a whole. It returns
// the names that were actually removed.
func (k *Kernel) Remove(names ...string) []string {
	k.mu.Lock()
	defer k.mu.Unlock()
	want := map[string]bool{}
	for _, n := range names {
		want[n] = true
	}
	matches := func(n string) bool {
		typ, _, isMethod := strings.Cut(n, ".")
		return want[n] || (isMethod && want[typ])
	}
	var removed []string
	decls := k.decls[:0:0]
	for _, d := range k.decls {
		if slices.ContainsFunc(d.Names, matches) {
			for _, n := range d.Names {
				if !strings.Contains(n, "#") {
					removed = append(removed, n)
				}
			}
			continue
		}
		decls = append(decls, d)
	}
	imps := k.imports[:0:0]
	for _, i := range k.imports {
		if want[i.Path] || (i.Name != "" && want[i.Name]) {
			removed = append(removed, strconv.Quote(i.Path))
			continue
		}
		imps = append(imps, i)
	}
	k.decls, k.imports = decls, imps
	return removed
}

func (k *Kernel) environ() []string {
	env := os.Environ()
	env = append(env, "GOPYTER_CACHE_DIR="+k.CacheDir())
	for key, v := range k.env {
		env = append(env, key+"="+v)
	}
	return env
}

// Execute runs a cell. cellID identifies the cell (re-executing a cell
// replaces its previous declarations), name is used in error positions.
// Output is streamed through emit; calls to emit are serialized.
func (k *Kernel) Execute(ctx context.Context, cellID, name, src string, emit func(Event)) error {
	// Output arrives from several goroutines (stdout, stderr, display);
	// serialize it so emit never needs to be safe for concurrent use.
	var emitMu sync.Mutex
	unsafeEmit := emit
	emit = func(e Event) {
		emitMu.Lock()
		defer emitMu.Unlock()
		unsafeEmit(e)
	}

	pc, err := parseCell(cellID, name, src)
	if err != nil {
		emit(Event{Kind: Error, Text: cleanErrors(err.Error(), k.Dir)})
		return ErrCompile
	}

	for _, c := range pc.commands {
		if err := k.runCommand(ctx, c, emit); err != nil {
			return err
		}
	}
	if !pc.hasCode {
		return nil
	}

	decls, imps := k.merge(cellID, pc)
	mainPath := filepath.Join(k.Dir, "main.go")
	var resolved []*Import
	write := func() error {
		var src string
		src, resolved = k.generate(decls, imps, pc)
		return os.WriteFile(mainPath, []byte(src), 0o644)
	}
	if err := write(); err != nil {
		return err
	}

	bin := filepath.Join(k.Dir, "gopyter_exec")
	if runtime.GOOS == "windows" {
		bin += ".exe"
	}
	fetched := false
	for {
		out, err := k.goCmd(ctx, "build", "-o", bin, ".").CombinedOutput()
		if ctx.Err() != nil {
			return ErrInterrupted
		}
		if err == nil {
			break
		}
		if pc.body != pc.plain && strings.Contains(string(out), "used as value") {
			// The trailing call returns no value: don't display it.
			pc.body = pc.plain
			if err := write(); err != nil {
				return err
			}
			continue
		}
		if missing := missingModules(string(out)); !fetched && len(missing) > 0 {
			fetched = true
			for _, p := range missing {
				emit(Event{Kind: Info, Text: "go get " + p})
				if gout, gerr := k.goCmd(ctx, "get", p).CombinedOutput(); gerr != nil {
					emit(Event{Kind: Error, Text: strings.TrimSpace(string(gout))})
					return ErrCompile
				}
			}
			continue
		}
		emit(Event{Kind: Error, Text: cleanErrors(string(out), k.Dir)})
		return ErrCompile
	}

	// Compilation succeeded: commit the declarations.
	k.mu.Lock()
	k.decls, k.imports, k.resolved = decls, imps, resolved
	args := append([]string(nil), k.args...)
	k.mu.Unlock()

	return k.run(ctx, bin, args, emit)
}

func (k *Kernel) merge(cellID string, pc *parsedCell) ([]*Decl, []*Import) {
	k.mu.Lock()
	defer k.mu.Unlock()
	newNames := map[string]bool{}
	for _, d := range pc.decls {
		for _, n := range d.Names {
			newNames[n] = true
		}
	}
	var decls []*Decl
	for _, d := range k.decls {
		if d.CellID == cellID {
			continue
		}
		clash := false
		for _, n := range d.Names {
			if newNames[n] {
				clash = true
				break
			}
		}
		if !clash {
			decls = append(decls, d)
		}
	}
	for _, d := range pc.decls {
		k.seq++
		d.seq = k.seq
		decls = append(decls, d)
	}

	newPaths := map[string]bool{}
	for _, i := range pc.imports {
		newPaths[i.Path] = true
	}
	var imps []*Import
	for _, i := range k.imports {
		if i.CellID != cellID && !newPaths[i.Path] {
			imps = append(imps, i)
		}
	}
	imps = append(imps, pc.imports...)
	return decls, imps
}

func writeImports(b *strings.Builder, imps []*Import) {
	if len(imps) == 0 {
		return
	}
	b.WriteString("import (\n")
	for _, i := range imps {
		b.WriteString("\t")
		if i.Name != "" {
			b.WriteString(i.Name)
			b.WriteString(" ")
		}
		b.WriteString(strconv.Quote(i.Path))
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

func (k *Kernel) generate(decls []*Decl, imps []*Import, pc *parsedCell) (string, []*Import) {
	var body strings.Builder
	for _, d := range decls {
		body.WriteString(d.Src)
		body.WriteString("\n\n")
	}
	if pc.userMain != "" {
		body.WriteString(pc.userMain)
		body.WriteString("\n")
	} else {
		body.WriteString("func main() {\n")
		body.WriteString(pc.body)
		body.WriteString("\n}\n")
	}

	var draft strings.Builder
	draft.WriteString("package main\n\n")
	writeImports(&draft, imps)
	draft.WriteString(body.String())

	// Let goimports add missing and remove unused imports, then keep only
	// the resulting import list so our //line directives stay intact.
	finalImps := imps
	if fixed, err := imports.Process(filepath.Join(k.Dir, "main.go"), []byte(draft.String()), nil); err == nil {
		if f, err := parser.ParseFile(token.NewFileSet(), "", fixed, parser.ImportsOnly); err == nil {
			finalImps = nil
			for _, is := range f.Imports {
				imp := &Import{Path: strings.Trim(is.Path.Value, "\"`")}
				if is.Name != nil {
					imp.Name = is.Name.Name
				}
				finalImps = append(finalImps, imp)
			}
		}
	}

	var out strings.Builder
	out.WriteString("// Code generated by gopyter. DO NOT EDIT.\npackage main\n\n")
	writeImports(&out, finalImps)
	out.WriteString(body.String())
	return out.String(), finalImps
}

var missingRe = regexp.MustCompile(`no required module provides package ([^\s;:]+)`)

func missingModules(out string) []string {
	seen := map[string]bool{}
	var res []string
	for _, m := range missingRe.FindAllStringSubmatch(out, -1) {
		if !seen[m[1]] {
			seen[m[1]] = true
			res = append(res, m[1])
		}
	}
	return res
}

func cleanErrors(s, dir string) string {
	var out []string
	for l := range strings.SplitSeq(strings.TrimSpace(s), "\n") {
		if strings.HasPrefix(l, "# ") {
			continue
		}
		l = strings.ReplaceAll(l, dir+string(filepath.Separator), "")
		l = strings.TrimPrefix(l, "./")
		out = append(out, l)
	}
	return strings.Join(out, "\n")
}

func (k *Kernel) run(ctx context.Context, bin string, args []string, emit func(Event)) error {
	cmd := exec.CommandContext(ctx, bin, args...)
	cmd.Dir = k.RunDir
	cmd.Env = k.environ()
	cmd.WaitDelay = 2 * time.Second
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return err
	}
	// Rich results (Display/DisplayMarkdown) are sent through file
	// descriptor 3; on Windows they fall back to stdout.
	dr, dw, err := os.Pipe()
	if err != nil {
		return err
	}
	if runtime.GOOS != "windows" {
		cmd.ExtraFiles = []*os.File{dw}
	}
	if err := cmd.Start(); err != nil {
		_ = dr.Close()
		_ = dw.Close()
		return err
	}
	// The child holds its own copy of the write end.
	_ = dw.Close()

	var wg sync.WaitGroup
	wg.Add(3)
	go func() { defer wg.Done(); pump(stdout, Stdout, emit) }()
	go func() { defer wg.Done(); pump(stderr, Stderr, emit) }()
	go func() {
		defer wg.Done()
		defer func() { _ = dr.Close() }()
		sc := bufio.NewScanner(dr)
		sc.Buffer(make([]byte, 64*1024), 64*1024*1024)
		for sc.Scan() {
			var m struct{ Mime, Data string }
			if json.Unmarshal(sc.Bytes(), &m) != nil {
				continue
			}
			kind := Result
			if m.Mime == "text/markdown" {
				kind = Markdown
			}
			emit(Event{Kind: kind, Text: m.Data})
		}
		if err := sc.Err(); err != nil {
			emit(Event{Kind: Error, Text: "display output: " + err.Error()})
			// Keep draining so the program never blocks on a full pipe.
			_, _ = io.Copy(io.Discard, dr)
		}
	}()
	wg.Wait()
	err = cmd.Wait()
	if ctx.Err() != nil {
		return ErrInterrupted
	}
	if ee, ok := errors.AsType[*exec.ExitError](err); ok {
		return fmt.Errorf("exit status %d", ee.ExitCode())
	}
	return err
}

func pump(r io.Reader, kind EventKind, emit func(Event)) {
	buf := make([]byte, 32*1024)
	for {
		n, err := r.Read(buf)
		if n > 0 {
			emit(Event{Kind: kind, Text: string(bytes.Clone(buf[:n]))})
		}
		if err != nil {
			return
		}
	}
}

// runCommand executes a shell command or magic.
func (k *Kernel) runCommand(ctx context.Context, c Command, emit func(Event)) error {
	if !c.Magic {
		shell, flag := "sh", "-c"
		if runtime.GOOS == "windows" {
			shell, flag = "cmd", "/C"
		}
		cmd := exec.CommandContext(ctx, shell, flag, c.Text)
		cmd.Dir = k.Dir
		cmd.Env = append(k.environ(), "GOWORK=off")
		stdout, _ := cmd.StdoutPipe()
		stderr, _ := cmd.StderrPipe()
		if err := cmd.Start(); err != nil {
			return err
		}
		var wg sync.WaitGroup
		wg.Add(2)
		go func() { defer wg.Done(); pump(stdout, Stdout, emit) }()
		go func() { defer wg.Done(); pump(stderr, Stderr, emit) }()
		wg.Wait()
		if err := cmd.Wait(); err != nil {
			if ctx.Err() != nil {
				return ErrInterrupted
			}
			return fmt.Errorf("!%s: %w", c.Text, err)
		}
		return nil
	}

	fields := strings.Fields(c.Text)
	if len(fields) == 0 {
		return nil
	}
	switch fields[0] {
	case "reset":
		k.Reset()
		emit(Event{Kind: Info, Text: "kernel state cleared"})
	case "env":
		if len(fields) == 1 {
			k.mu.Lock()
			for key, v := range k.env {
				emit(Event{Kind: Stdout, Text: key + "=" + v + "\n"})
			}
			k.mu.Unlock()
			return nil
		}
		for _, kv := range fields[1:] {
			key, v, ok := strings.Cut(kv, "=")
			if !ok {
				return fmt.Errorf("%%env: expected KEY=VALUE, got %q", kv)
			}
			k.mu.Lock()
			k.env[key] = v
			k.mu.Unlock()
			emit(Event{Kind: Info, Text: "set " + key})
		}
	case "args":
		k.mu.Lock()
		k.args = fields[1:]
		k.mu.Unlock()
		emit(Event{Kind: Info, Text: "program args: " + strings.Join(fields[1:], " ")})
	case "rm":
		if len(fields) == 1 {
			return errors.New("%rm: expected names to remove (see %ls)")
		}
		if removed := k.Remove(fields[1:]...); len(removed) == 0 {
			emit(Event{Kind: Info, Text: "nothing to remove"})
		} else {
			emit(Event{Kind: Info, Text: "removed " + strings.Join(removed, ", ")})
		}
	case "cache":
		return k.cacheMagic(fields[1:], emit)
	case "ls", "who":
		names := k.Declarations()
		if len(names) == 0 {
			emit(Event{Kind: Info, Text: "no declarations"})
		} else {
			emit(Event{Kind: Stdout, Text: strings.Join(names, "\n") + "\n"})
		}
	case "workspace":
		emit(Event{Kind: Stdout, Text: k.Dir + "\n"})
	case "help":
		emit(Event{Kind: Markdown, Text: MagicHelp})
	default:
		return fmt.Errorf("unknown magic %%%s (try %%help)", fields[0])
	}
	return nil
}

func (k *Kernel) cacheMagic(args []string, emit func(Event)) error {
	if len(args) == 0 {
		keys, err := k.CacheKeys()
		if err != nil {
			return err
		}
		if len(keys) == 0 {
			emit(Event{Kind: Info, Text: "cache is empty"})
		} else {
			emit(Event{Kind: Stdout, Text: strings.Join(keys, "\n") + "\n"})
		}
		return nil
	}
	if args[0] != "clear" {
		return fmt.Errorf("%%cache: unknown subcommand %q (use %%cache or %%cache clear [keys])", args[0])
	}
	removed, err := k.ClearCache(args[1:]...)
	if err != nil {
		return err
	}
	if len(removed) == 0 {
		emit(Event{Kind: Info, Text: "nothing to clear"})
	} else {
		emit(Event{Kind: Info, Text: "cleared " + strings.Join(removed, ", ")})
	}
	return nil
}

// MagicHelp documents the special cell commands.
const MagicHelp = "## Cell commands\n\n" +
	"| Command | Description |\n|---|---|\n" +
	"| `!cmd` | run a shell command in the kernel workspace (e.g. `!go get github.com/foo/bar`) |\n" +
	"| `%reset` | forget all declarations |\n" +
	"| `%env KEY=VALUE` | set environment variables for executed programs |\n" +
	"| `%args a b c` | set command line arguments for executed programs |\n" +
	"| `%ls` | list persisted declarations |\n" +
	"| `%rm name...` | forget declarations (a type's methods too) or imports |\n" +
	"| `%cache` | list values stored by `Cache`/`CacheErr` |\n" +
	"| `%cache clear [key...]` | delete cached values so they are recomputed |\n" +
	"| `%workspace` | print the kernel workspace directory |\n\n" +
	"Top level `func`, `type`, `var`, `const` and `import` declarations persist across cells. " +
	"Everything else runs inside `main()`. A trailing expression is displayed as the result. " +
	"Use `Display(v)` and `DisplayMarkdown(s)` for rich output.\n\n" +
	"Each cell runs in a fresh process, so a persisted `var` is re-initialized every time. " +
	"Wrap expensive initializers to compute them once: " +
	"`var resp, err = CacheErr(\"resp\", func() (*T, error) { ... })`."
